language: python

addons:
  apt:
    packages:
      - libhdf5-dev

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.6
      dist: xenial
      sudo: true

install:
  - pip install tables

script:
  - python test.py

